# Generated by Django 4.0.4 on 2022-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPoint', models.CharField(max_length=30, verbose_name='startPoint')),
                ('finishPoint', models.CharField(max_length=30, verbose_name='finishPoint')),
                ('startTime', models.CharField(max_length=30, verbose_name='startTime')),
                ('finishTime', models.CharField(max_length=30, verbose_name='finishTime')),
                ('startDate', models.CharField(max_length=30, verbose_name='startDate')),
                ('finishDate', models.CharField(max_length=30, verbose_name='finishDate')),
                ('price', models.CharField(max_length=10)),
                ('sourceLink', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=30, verbose_name='login')),
            ],
        ),
    ]
