# Generated by Django 4.0.4 on 2022-05-24 10:24

from django.db import migrations
def create_data(apps, schema_editor):
    savedTickets = apps.get_model('savedTickets', 'savedTickets')
    savedTickets(startPoint="Тюмень", finishPoint="Екатеринбург", startTime="00:36", finishTime="08:46",
                 startDate="27 05", finishDate="27 05",
            price="850 руб", sourceLink="https://avs.io/1P7EV", login="admin").save()



class Migration(migrations.Migration):

    dependencies = [
        ('savedTickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
