# Generated by Django 4.0.4 on 2022-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPoint', models.CharField(max_length=30, verbose_name='startPoint')),
                ('finishPoint', models.CharField(max_length=30, verbose_name='finishPoint')),
                ('price', models.CharField(max_length=10)),
                ('sourceLink', models.CharField(max_length=150)),
                ('timeOnWay', models.CharField(max_length=150)),
            ],
        ),
    ]
