# Generated by Django 4.0.4 on 2022-05-20 08:45

from django.db import migrations

def create_data(apps, schema_editor):
    Tickets = apps.get_model('tickets', 'Tickets')
    Tickets(startPoint="Тюмень", finishPoint="Екатеринбург",
             price="850 руб", sourceLink="https://avs.io/1P7EV", timeOnWay="3ч 55м").save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]

